### ISSUE TITLE
Error on line #29 of ZCiCalNode.php

### ISSUE THREAD

**Issue by GraemeHalls** [phpfui/icalendar#3]
Hi. Thanks for forking this! 
Just trying to get it working, but I'm getting an error on line #29 of ZCiCalNode.php.

`PHP Parse error:  syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in **/events/ICalendarOrg/ZCiCalNode.php on line 29`

Looking in this file, its setting the following:
`public array $child = [];`

Should I be parsing anything else into this?

Thanks

**Comment by phpfui** [comment]
This library supports PHP 7.4 and higher only. It may be that the composer.json file is misconfigured. I will look into that this week.

What version of PHP are you using?

**Comment by phpfui** [comment]
I am going to close this, as the composer.json file is correctly configured.

I suspect your problem is you have higher version of PHP installed at the command line than your web server uses.  Type "php -v" at a command prompt to check.  Call phpinfo() from PHP to see what version of PHP your server is running.  I would recommend they be the same and to upgrade to PHP 8.1 if possible.
