### ISSUE TITLE
Carriage Returns missing in ICS Files

### ISSUE THREAD

**Issue by wavedeck** [phpfui/icalendar#5]
After following the "simpleevent.php" example, I noticed that the generated ICS files fail common online validators such as https://icalendar.org/validator.html due to missing carriage returns "CRLF".

I've tested the ```examples/simpleevent.php``` without further modification, saved the output of ```$icalobj->export()``` using PHP 8.2's ```fputs``` function and uploaded the generated file to the validator mentioned above.

**The error thrown is:**

Lines not delimited by CRLF sequence [near line # 1]
Reference: [RFC 5545 3.1. Content Lines](http://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html)

I know that carriage returns are a Windows specific thing, but just using linefeeds triggers validators.
It could be worth patching this.

**System Environment:**

Ubuntu 22.04 ARM64v8 (M1 Pro) in a VM
PHP 8.2 using Ondrej's PHP PPA

**Comment by wavedeck** [comment]
The following RFC section on the structure of icalendar files might be helpful

https://www.rfc-editor.org/rfc/rfc5545#section-3.1

**Comment by phpfui** [comment]
Thanks.  When I validate the simpleevent.php output, I just get a line too long warning.  But I am copy and pasting it from a Windows command line into the form.  I will try a more direct to file approach.

I had not paid any attention to the examples directory actually since I ported this library from the original version from ICalendar.org to modern PHP.

I did do some refactoring involving \n and \r stuff a while back.  Something may have broken. Do you know of any ICalendar validators that I can use in unit testing? I did this for HTML validation and it worked well.

**Comment by phpfui** [comment]
Yes, the direct file test confirms it is missing a carriage return. Will fix later today or tomorrow.

Thanks for the heads up.  I will also look into line length.

**Comment by wavedeck** [comment]
Great! Thanks for your commitment and the fact you are keeping the library alive.

The line-length (especially in the DESCRIPTION) occurs due to ics files expecting no more than 75 octets on a single line.

The RFC recommends a line-folding technique using a blank character such as a space followed by a CRLF. This could maybe be achievable by implementing a filter method that splits lines longer than 75 octets using the technique above.

In regards to unit-testable validators: Not of the top of my head. I will let you know however, if i encounter one during my icalendar journey.

**Comment by phpfui** [comment]
There is now a new release that correctly validates.  Let me know if you still have issues by opening a new issue.  Closing this as completed.
